# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life with Pi
email: anne.ayanian@gmail.com
sign_up: Fall math tutoring
description: > # this means to ignore newlines until "baseurl:"
  Anne Ayanian's hand-selected resources to aid your Life with Pi!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lifewithpi.com" # the base hostname & protocol for your site
twitter_username: AnneAyanian
github_username:  cayanian

# Build settings
markdown: kramdown
